VERSION 0.8

rust-builder:
    FROM rust:buster
    RUN apt-get update && apt-get install -y clang valgrind jq
    RUN rustup component add clippy
    # cargo-nextest, buildcache
    COPY ./apps/* /usr/local/bin
    # cargo config with buildcache wrapper
    COPY ./files/.cargo ~/.cargo

reth:
    FROM +rust-builder
    GIT CLONE https://github.com/paradigmxyz/reth reth
    ENV RUST_BACKTRACE 1
    WORKDIR reth
